
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: actuator_demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8242/terra?characterEncoding=UTF-8
    #    url: jdbc:mariadb://terra-db:3306/ksos?characterEncoding=UTF-8
    username: terra
    password: terra



management:
  server:
    port: 8081 # actuator? ?? ??? ?? ??
  endpoints:
    web:
      base-path: "/manage" # ?? URL actuator -> manage ??
      exposure:
        include: "*"  # ?? ????? ??
#        include: health, metrics, info # ??? ?????
#        exclude: env, beans            # ??? ?????
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    env:
      show-values: always # ???? **** ? ?? 
  health:
    db:
      enabled: false
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: actuator_demo
    version: ${appVersion}
    contact:
      email: shbae@raoncorp.com
      phone: 02-1234-1234




# Actuator? ???? ??? ?? ??? ?? ???? ???
# ??? ???? ??? ??? ??? ? ??.
# ??????? ?? ??? ????? ??, ?????
# ??? ???? ???? ?? ????
#  ??? ?? ??? ???? ???? ??


# health ? detail ? ???? ???? ????
# ?? ??? ???? ???? ??? ? ? ??
# ? ?? ?????? API ???? ??? ? ??
#


#
# ??? ?? Actuator? ??????? ?? ? ??? ????? ?????? ??? ? ?? ??? ?????. ?? ???? ????? ?????, ??????? ???? ???? ???, ??? ??? ??? ? ?? ????.

# ??? ?? ????
# ??? ?? ? ?? ???? -> ??????, ????
# ?? ?? ??
# ??? ? ?? ????
# ?????? ?? ?? -> ?? ?
# ?? ??
